num1 = input("Enter the first number : ")
num2 = input("Enter the anothe numbere : ")
add = float(num1)+float(num2)
sub = float(num1)-float(num2)
multiply=float(num1)+float(num2)
div =float(num1)+float(num2)
mod=float(num1)%float(num2)
print("Welcome to gpa calculeter ")
print(add)
print(sub)
print(div)
print(mod)
print(multiply)